language: python
python:
  - '2.6'
  - '2.7'
  - '3.3'
  - '3.4'
  - '3.5'
  - '3.6'
  - 'nightly'
install:
  - pip install .
before_script:
  - pip install coveralls "pytest>=2.8" pytest-runner
script:
  - coverage run ./setup.py test
after_success:
  - coveralls
cache: pip
deploy:
  - provider: pypi
    user: duncanmmacleod
    password:
      secure: AWHqZruQMW9uHIhXLlKwgdfWBHZIgwLtvkP7D+al4zYG/wSOvZDTT7ZsxOhFogYxIXWzwcBIPYgUGplkMOlb+N0Wl45OPL6U2tN5EtUEtWnTd/OxrDzA/DJJbgdfy4VqFSj0fY7FTBNJCeCciZ+TmtBrcWSFbHorrLyF5oOW7VQ=
    on:
      branch: master
      tags: true
      distributions: sdist bdist_wheel
      repo: lscsoft/ligotimegps
