language: python
python:
  - '2.6'
  - '2.7'
  - '3.2'
  - '3.3'
  - '3.4'
  - '3.5'
  - '3.6'
  - 'nightly'
install:
  - pip install .
script:
  - coverage run ./setup.py test
after_success:
  - coveralls
cache: pip
